services:
  shl-creator:
    # only need to change image tag for dev if node modules are updated
    image: ghcr.io/uwcirg/shl-ips:${SHL_CREATOR_IMAGE_TAG:-latest}-dev
    environment:
      SERVER_NAME: ${BASE_DOMAIN}
    command: npm run dev

    volumes:
      - ${SHL_CREATOR_CHECKOUT_DIR}:/opt/app
      - node_modules:/opt/app/node_modules
      - svelte-kit:/opt/app/.svelte-kit

volumes:
  node_modules:
  svelte-kit:
